---
title       : CMASF Graphics Example
subtitle    : 
author      : Irina Goloshchapova
job         : Expert
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Crisis Pulse
- 3 - high probability
- 2 - medium probability
- 1 - low probability

```{r ggauge, echo = FALSE, results='asis', warning = FALSE, message = FALSE}
library(googleVis)
ind <- data.frame(Indicator = c("Crisis", "NPL", "Liquidity", "Exch.rate"),
                  Probability = c(3, 3, 1, 2))
ind$Indicator <- factor(as.character(ind$Indicator))
Gauge <-  gvisGauge(ind, options=list(min=0, max=3, greenFrom=0, 
                                      greenTo=1.5, yellowFrom=1.5, yellowTo=2.5,
                                      redFrom=2.5, redTo=3, 
                                      width = 400, height = 600))
plot(Gauge, tag = "chart")
```

---
## System Bank crisis probability

<iframe src="https://plot.ly/~IrinaGoloshchapova/40/none/" width="800" height="500" scrolling="no" frameBorder="0"></iframe>

<span class="footnote">Data source: CMASF</span>

---
## System bank crisis probability 
Playing with Google Graphics

```{r gannotation, echo = FALSE, message = FALSE, results = 'asis'}
library(reshape)
bank.crisis.indicator <- c(0.133, 0.136, 0.130, 0.123, 0.121, 0.113, 0.112, 
              0.112, 0.107, 0.109, 0.110, 0.105, 0.110, 0.099, 
              0.087, 0.083, 0.088)
bank.crisis.ending.indicator <- c(0.110, 0.116, 0.116, 0.122, 0.132, 0.125, 0.120, 
            0.123, 0.108, 0.110, 0.103, 0.099, 0.104, 0.118, 
            0.131, 0.145, 0.162)
date <- seq(as.Date("2014/1/1"), as.Date("2015/5/1"), "month")
title <- ifelse(date == "2014/12/1", "Crisis", NA)
title <- factor(title)
annotation <- ifelse(date == "2014/12/1", "System bank crisis occurs 
                     according to the Demirguc-Kunt 
                     and Detragiache definition", NA)
annotation <- factor(annotation)

data <- data.frame(date, bank.crisis.indicator, bank.crisis.ending.indicator, title, annotation)
md <- as.data.frame(melt(data, id = c("date", "title", "annotation")))
md$variable <- factor(md$variable)

Annot <- gvisAnnotationChart(md, 
                             datevar = "date",
                             numvar = "value",
                             idvar = "variable",
                             options=list(width=600, height=350,
                                          fill=10, displayExactValues=TRUE,
                                          colors="['#0000ff','#00ff00']"))

plot(Annot, tag = "chart")
```

